Capston project week 5
ridwanediallo/Conference-page pull request #1
Opened 2022-02-04 07:13 UTC by ridwanediallo

2022-02-04 18:10 UTC, moise10r requested changes
### Hi **@ridwanediallo,**

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻


* Good commit messages ✔️ 
* Professional README ✔️ 
* Demonstrate ability to create UIs adaptable to different screen sizes using media queries.✔️  
* Use GitHub Pages to deploy web pages. ✔️  
* Apply JavaScript best practices and language style guides in code. ✔️  
* Your Design looks awesome, keep rocking :rocket: 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Your README looks great 👍🏻 but I think you can improve it by making it more professional. A professional README file should have a project title, project description, list of technology used in the project, a screenshot of your project and instructions to set the project up locally


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 18:10 UTC, moise10r commented on README.md
> +![screenshot](Conference-page\images\screen-mob.PNG)
- [ ] Great job on adding images of your website to your README👏 . However, they are not displaying yet, kindly fix this and make sure they are showing up correctly.

2022-02-04 18:10 UTC, moise10r commented on index.html
> +          </div>
- [ ] Great job on this section :+1:  but this while border should not be static, I think you can use the `:hover` CSS property to make it show up only if a user hover a `program` section, kindly make this also for all you `program` div

![1](https://user-images.githubusercontent.com/57562869/152573793-48f33abc-5ce9-41f2-8564-bb0306895a75.png)

2022-02-04 18:10 UTC, moise10r commented on styles.css
> +}
- [ ] There is an issue with the first speaker image which does not show up, kindly fix this to improve your design and make it more professional :arrow_down:

![2](https://user-images.githubusercontent.com/57562869/152574497-066c0f07-e431-4f9f-bc5f-1b8e5ff715be.png)

2022-02-04 18:10 UTC, moise10r commented on about.html
> +      </nav>
- [ ] You have implemented the header in a professional way. That's perfect 👏 . Let's make it better by changing the background-color to be lighter and  match the original background color design
- [ ] Kindly, do the same thing for the footer.

- header:

![3](https://user-images.githubusercontent.com/57562869/152575742-bea20669-436a-45ca-aebf-606493aaafa1.png)

- footer:

![4](https://user-images.githubusercontent.com/57562869/152575786-83953348-8c3a-496e-aecf-038582606607.png)

2022-02-04 18:10 UTC, moise10r commented on styles.css
> +} */
- [ ] Please do not leave unused code as a comment in your codebase. unused code as comments makes your code not clean. Kindly remove all unused code this will make your code mush noise, It is always a good practice to keep your code clean from such comments.

2022-02-04 18:10 UTC, moise10r commented on styles.css
> +  height: 100vh;
- [ ] Great job on this section :+1: However the background of the mobile navigation menu is transparent or the same color/pattern as the top section background, kindly to improve your design you can change the background color or you can make it transparent
- color swatch: #272A31, #EC5242, #D3D3D3

![5](https://user-images.githubusercontent.com/57562869/152577466-36c08c99-b42b-46e4-9b64-2f03c1939cef.png)

2022-02-04 18:10 UTC, moise10r commented on index.html
> +          <div class="program">
- [OPTIONAL] Great job  👏🏻 , however you could improve it by using a list tag instead, you can change the `divs` into   `li` and use `ul ` to group them,.  It could be something like this :point_down: 
-
    ```HTML 
                           <ul class="programs">
                               <li class="program"><...</li>
                               <li class="program">...</li>
                               <li class="program"> ...</li>
                           </ul>
     ```

2022-02-04 18:10 UTC, moise10r commented on styles.css
> +/* font-family: 'COCOGOOSE', sans-serif; */
- [ ] Please do not leave unused code as a comment in your codebase. unused code as comments makes your code not clean. Kindly remove all unused code this will make your code mush noise, It is always a good practice to keep your code clean from such comments.

2022-02-04 18:10 UTC, moise10r commented on about.html
> +      <div class="hero-content">
- [ ] I think it would be better if your home image could have a `width: 100%`  of the hero-content container :point_down: 

![two](https://user-images.githubusercontent.com/57562869/152580870-e41b8bfa-93d5-4d8a-bcf5-3d1a0d5ee498.png)

2022-02-04 23:15 UTC, Rustamxon7 requested changes
## STATUS: CHANGES REQUIRED 🟠
 Hi @ridwanediallo ,
 
 Great work on making the changes requested by the previous reviewer, but there are still some which aren't addressed yet.
 
 ## Required Changes ♻️
 _Check the comments under the review._
 
 ![really close](https://camo.githubusercontent.com/610ba39845cbc5bfce08f092117aa5573447b79bd89160db59ada95582b1836c/68747470733a2f2f632e74656e6f722e636f6d2f66754b6a7462743762344541414141642f7265616c6c792d7265616c6c792d636c6f73652d62696c6c2d6d75727261792e676966)
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 23:15 UTC, Rustamxon7 commented on about.css
> +  top: 0;
- [ ] Let's change the position absolute to fixed. It will fix the scrolling issue on mobile, so navigation always stays in one place even you scroll down 😀

2022-02-04 23:15 UTC, Rustamxon7 commented on about.css
> +}
- [ ] There is a difference between navigation in about page and an index page on mobile version 🤔. The first one is looking transparent and the second has a white background, let's make them look the same 👍

Index page
![image](https://user-images.githubusercontent.com/69011963/152615064-e88d22c1-ed9c-4f2e-a54a-5a0b2b52966e.png)

About page
![image](https://user-images.githubusercontent.com/69011963/152615111-e0957161-321e-43f2-8a60-5741aa8580a7.png)

2022-02-04 23:15 UTC, Rustamxon7 commented on styles.css
> +}
- [ ] This part of the design looks hard to read 😃. Let's fix it by adding white background there

Screenshot 📸
![image](https://user-images.githubusercontent.com/69011963/152615387-1142bbff-e3a3-4900-8e53-7e37bfcbbdb4.png)

2022-02-04 23:15 UTC, Rustamxon7 commented on about.css
> +  } */
- [ ] As the previous review suggested please also remove the unused code from the CSS file 👌

2022-02-05 00:31 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 
Hi @ridwanediallo , 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)
Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

```

2022-02-05 06:59 UTC, merged